<a href="https://colab.research.google.com/github/ignacio07-ops/Networking-Lab-Project/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing  the datas

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
df_supporter = pd.read_csv("supporter.csv")
df_campaigns = pd.read_csv("campaigns_events.csv")
df_communications = pd.read_csv("communications.csv")
df_donations = pd.read_csv("donations.csv")

Exploring the datasets

In [11]:
datasets = {
    "supporter": df_supporter,
    "campaigns_events": df_campaigns,
    "communications": df_communications,
    "donations": df_donations
}

for name, dataset in datasets.items():
    print(f"--- Null values in {name} ---")
    print(dataset.isnull().any())
    print("\n") # Add a blank line for readability

--- Null values in supporter ---
supporter_id                     False
registration_date                False
registration_channel             False
marketing_opt_in                 False
preferred_channel                False
date_of_birth                    False
address_postcode                 False
address_state                     True
address_country                  False
gender                            True
helix_community                   True
login_count_last_12m             False
donation_page_visits_last_12m    False
last_login_date                  False
dtype: bool


--- Null values in campaigns_events ---
campaign_id       False
campaign_type     False
campaign_theme    False
start_date        False
end_date          False
dtype: bool


--- Null values in communications ---
contact_id         False
supporter_id       False
campaign_id        False
contact_date       False
contact_channel    False
message_type       False
delivered          False
opened             False
clicked            False
dtype: bool


--- Null values in donations ---
donation_id        False
supporter_id       False
donation_date      False
donation_amount    False
payment_channel    False
campaign_id        False
dtype: bool

In [12]:
for name, dataset in datasets.items():
    print(f"--- Head of {name} ---")
    display(dataset.head())
    print("\n") # Add a blank line for readability

--- Head of supporter ---

,supporter_id,registration_date,registration_channel,marketing_opt_in,preferred_channel,date_of_birth,address_postcode,address_state,address_country,gender,helix_community,login_count_last_12m,donation_page_visits_last_12m,last_login_date
0,100000,30/04/2022,Website,1,email,1/10/1981,7395,TAS,Australia,f,100.0,33,13,22/09/2025
1,100001,26/07/2021,Event,1,email,3/03/1968,7363,TAS,Australia,F,300.0,4,2,17/05/2025
2,100002,17/05/2021,Website,1,sms,10/11/1954,6282,WA,Australia,Female,600.0,1,0,16/04/2025
3,100003,17/05/2022,Social Media,0,email,1/11/1952,5641,SA,Australia,f,200.0,27,11,29/12/2025
4,100004,29/05/2019,Website,1,whatsapp,30/05/1956,851,NT,Australia,F,200.0,6,1,6/09/2025

--- Head of campaigns_events ---

,campaign_id,campaign_type,campaign_theme,start_date,end_date
0,30000,Event,Healthcare Access,14/05/2024,12/07/2024
1,30001,Digital Campaign,Healthcare Access,10/10/2023,27/12/2023
2,30002,Regular Giving Program,Safe Water Initiative,19/10/2025,31/12/2025
3,30003,Digital Campaign,Healthcare Access,18/08/2025,27/10/2025
4,30004,Digital Campaign,Safe Water Initiative,25/07/2023,22/09/2023

--- Head of communications ---

,contact_id,supporter_id,campaign_id,contact_date,contact_channel,message_type,delivered,opened,clicked
0,5000016.0,106219,30037,2022-07-27,sms,Newsletter,1,0,0
1,5000105.0,109774,30037,2022-08-07,facebook_message,Newsletter,1,0,0
2,5000206.0,111187,30037,2022-07-30,whatsapp,Donation Appeal,1,0,0
3,5000220.0,114476,30037,2022-07-23,whatsapp,Impact Story,1,0,0
4,5000336.0,103363,30037,2022-08-06,email,Donation Appeal,1,1,0

--- Head of donations ---

,donation_id,supporter_id,donation_date,donation_amount,payment_channel,campaign_id
0,90000000,108007,2022-06-18,20,Online,30026
1,90000222,108007,2022-03-01,37,Online,30024
2,90001012,108007,2022-07-07,21,Event,30039
3,90001743,108007,2023-05-10,20,Online,30012
4,90004927,108007,2025-12-26,32,Online,30011

In [15]:
for name, dataset in datasets.items():
    print(f"--- Head of {name} ---")
    display(dataset.dtypes)
    print("\n") # Add a blank line for readability

--- Head of supporter ---

supporter_id                       int64
registration_date                 object
registration_channel              object
marketing_opt_in                   int64
preferred_channel                 object
date_of_birth                     object
address_postcode                   int64
address_state                     object
address_country                   object
gender                            object
helix_community                  float64
login_count_last_12m               int64
donation_page_visits_last_12m      int64
last_login_date                   object
dtype: object

--- Head of campaigns_events ---

campaign_id        int64
campaign_type     object
campaign_theme    object
start_date        object
end_date          object
dtype: object

--- Head of communications ---

contact_id         float64
supporter_id         int64
campaign_id          int64
contact_date        object
contact_channel     object
message_type        object
delivered            int64
opened               int64
clicked              int64
dtype: object

--- Head of donations ---

donation_id         int64
supporter_id        int64
donation_date      object
donation_amount     int64
payment_channel    object
campaign_id         int64
dtype: object

In [17]:
print(df_supporter["registration_channel"].unique())
print(df_supporter["marketing_opt_in"].unique())
print(df_supporter["preferred_channel"].unique())
print(df_supporter["address_state"].unique())
print(df_supporter["address_country"].unique())
print(df_supporter["gender"].unique())
print(df_supporter["last_login_date"].unique())

['Website' 'Event' 'Social Media' 'Partner' 'Referral']
[1 0]
['email' 'sms' 'whatsapp' 'facebook_message']
['TAS' 'WA' 'SA' 'NT' 'VIC' 'QLD' 'NSW' 'ACT' nan]
['Australia']
['f' 'F' 'Female' 'M' 'm' 'Male' nan]
['22/09/2025' '17/05/2025' '16/04/2025' ... '7/11/2024' '18/10/2023'
 '19/12/2021']

In [19]:
# Define a threshold for how many unique values to display to avoid excessive output
max_unique_to_display = 10

for name, dataset in datasets.items():
    print(f"--- Unique values for object columns in {name} ---")
    for column in dataset.select_dtypes(include='object').columns:
        unique_vals = dataset[column].unique()
        print(f"  {column} ({len(unique_vals)} unique values):")
        if len(unique_vals) <= max_unique_to_display:
            print(f"    {unique_vals}")
        else:
            print(f"    [Showing first {max_unique_to_display} unique values] {unique_vals[:max_unique_to_display]}...")
    print("\n")

--- Unique values for object columns in supporter ---
  registration_date (2555 unique values):
    [Showing first 10 unique values] ['30/04/2022' '26/07/2021' '17/05/2021' '17/05/2022' '29/05/2019'
 '19/11/2025' '8/07/2023' '13/11/2019' '29/01/2024' '7/12/2019']...
  registration_channel (5 unique values):
    ['Website' 'Event' 'Social Media' 'Partner' 'Referral']
  preferred_channel (4 unique values):
    ['email' 'sms' 'whatsapp' 'facebook_message']
  date_of_birth (11569 unique values):
    [Showing first 10 unique values] ['1/10/1981' '3/03/1968' '10/11/1954' '1/11/1952' '30/05/1956'
 '21/05/1993' '10/03/1966' '17/09/1985' '8/09/1958' '30/11/2002']...
  address_state (9 unique values):
    ['TAS' 'WA' 'SA' 'NT' 'VIC' 'QLD' 'NSW' 'ACT' nan]
  address_country (1 unique values):
    ['Australia']
  gender (7 unique values):
    ['f' 'F' 'Female' 'M' 'm' 'Male' nan]
  last_login_date (1181 unique values):
    [Showing first 10 unique values] ['22/09/2025' '17/05/2025' '16/04/2025' '29/12/2025' '6/09/2025'
 '19/11/2025' '8/07/2023' '29/03/2025' '16/11/2025' '30/06/2025']...


--- Unique values for object columns in campaigns_events ---
  campaign_type (3 unique values):
    ['Event' 'Digital Campaign' 'Regular Giving Program']
  campaign_theme (5 unique values):
    ['Healthcare Access' 'Safe Water Initiative' 'Child Education'
 'Nutrition Program' 'Emergency Relief']
  start_date (49 unique values):
    [Showing first 10 unique values] ['14/05/2024' '10/10/2023' '19/10/2025' '18/08/2025' '25/07/2023'
 '11/11/2023' '18/05/2022' '20/02/2025' '1/11/2023' '8/06/2023']...
  end_date (42 unique values):
    [Showing first 10 unique values] ['12/07/2024' '27/12/2023' '31/12/2025' '27/10/2025' '22/09/2023'
 '31/12/2023' '16/07/2022' '21/05/2025' '12/08/2023' '30/08/2024']...


--- Unique values for object columns in communications ---
  contact_date (1240 unique values):
    [Showing first 10 unique values] ['2022-07-27' '2022-08-07' '2022-07-30' '2022-07-23' '2022-08-06'
 '2022-08-05' '2022-07-28' '2022-08-09' '2022-07-22' '2022-07-24']...
  contact_channel (4 unique values):
    ['sms' 'facebook_message' 'whatsapp' 'email']
  message_type (4 unique values):
    ['Newsletter' 'Donation Appeal' 'Impact Story' 'Event Invitation']


--- Unique values for object columns in donations ---
  donation_date (1240 unique values):
    [Showing first 10 unique values] ['2022-06-18' '2022-03-01' '2022-07-07' '2023-05-10' '2025-12-26'
 '2025-11-29' '2022-11-06' '2023-11-22' '2022-02-26' '2022-07-24']...
  payment_channel (3 unique values):
    ['Online' 'Event' 'Bank Transfer']

## Data Cleaning and Preprocessing

### 1. Convert Date Columns to Datetime Objects

Many columns identified as `object` type are actually dates. Converting them to `datetime` objects will allow for proper time-series analysis and calculations. We'll iterate through each DataFrame and convert the relevant columns.

In [20]:
# Define date columns for each DataFrame
date_columns = {
    'supporter': ['registration_date', 'date_of_birth', 'last_login_date'],
    'campaigns_events': ['start_date', 'end_date'],
    'communications': ['contact_date'],
    'donations': ['donation_date']
}

for name, df in datasets.items():
    for col in date_columns.get(name, []):
        if col in df.columns:
            # Using infer_datetime_format=True can speed up parsing
            # Using errors='coerce' will turn unparseable dates into NaT (Not a Time)
            datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
            print(f"Converted '{col}' in '{name}' to datetime.")

# Verify data types after conversion
for name, df in datasets.items():
    print(f"\n--- dtypes after date conversion for {name} ---")
    print(df.dtypes)

Converted 'registration_date' in 'supporter' to datetime.
Converted 'date_of_birth' in 'supporter' to datetime.
Converted 'last_login_date' in 'supporter' to datetime.
Converted 'start_date' in 'campaigns_events' to datetime.
Converted 'end_date' in 'campaigns_events' to datetime.
Converted 'contact_date' in 'communications' to datetime.
Converted 'donation_date' in 'donations' to datetime.

--- dtypes after date conversion for supporter ---
supporter_id                              int64
registration_date                datetime64[ns]
registration_channel                     object
marketing_opt_in                          int64
preferred_channel                        object
date_of_birth                    datetime64[ns]
address_postcode                          int64
address_state                            object
address_country                          object
gender                                   object
helix_community                         float64
login_count_last_12m                      int64
donation_page_visits_last_12m             int64
last_login_date                  datetime64[ns]
dtype: object

--- dtypes after date conversion for campaigns_events ---
campaign_id                int64
campaign_type             object
campaign_theme            object
start_date        datetime64[ns]
end_date          datetime64[ns]
dtype: object

--- dtypes after date conversion for communications ---
contact_id                float64
supporter_id                int64
campaign_id                 int64
contact_date       datetime64[ns]
contact_channel            object
message_type               object
delivered                   int64
opened                      int64
clicked                     int64
dtype: object

--- dtypes after date conversion for donations ---
donation_id                 int64
supporter_id                int64
donation_date      datetime64[ns]
donation_amount             int64
payment_channel            object
campaign_id                 int64
dtype: object

/tmp/ipykernel_1276/3031920183.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)
/tmp/ipykernel_1276/3031920183.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  datasets[name][col] = pd.to_datetime(df[col], errors='coerce', infer_datetime_format=True)

### 2. Clean `df_supporter` - Gender Column

The `gender` column has inconsistent entries (e.g., 'f', 'F', 'Female', 'M', 'm', 'Male'). We will standardize these to 'Female', 'Male', and 'Unknown' for better consistency and analysis. We'll also handle `NaN` values here.

In [24]:
# Standardize 'gender' column
df_supporter['gender'] = df_supporter['gender'].str.lower().replace({
    'f': 'female',
    'm': 'male'
}).fillna('unknown') # Fill NaN with 'unknown'

df_supporter['gender'] = df_supporter['gender'].replace({'female': 'Female', 'male': 'Male'})

print("Unique values in 'gender' after cleaning:")
print(df_supporter['gender'].unique())

Unique values in 'gender' after cleaning:
['Female' 'Male' 'unknown']

### 3. Handle Missing Values in `df_supporter` - `address_state`

The `address_state` column contains `NaN` values. We will fill these missing values with 'Unknown' to explicitly categorize them rather than leaving them as missing.

In [25]:
# Fill NaN values in 'address_state' with 'Unknown'
df_supporter['address_state'] = df_supporter['address_state'].fillna('Unknown')

print("Unique values in 'address_state' after cleaning:")
print(df_supporter['address_state'].unique())

Unique values in 'address_state' after cleaning:
['TAS' 'WA' 'SA' 'NT' 'VIC' 'QLD' 'NSW' 'ACT' 'Unknown']

### 4. Verify Cleaning Results

Let's check the info and the head of `df_supporter` to see the impact of our cleaning, especially the data types and the `gender` and `address_state` columns.

In [26]:
print("--- df_supporter info after cleaning ---")
df_supporter.info()
print("\n--- df_supporter head after cleaning ---")
display(df_supporter.head())

--- df_supporter info after cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   supporter_id                   17981 non-null  int64
 1   registration_date              17981 non-null  datetime64[ns]
 2   registration_channel           17981 non-null  object
 3   marketing_opt_in               17981 non-null  int64
 4   preferred_channel              17981 non-null  object
 5   date_of_birth                  11358 non-null  datetime64[ns]
 6   address_postcode               17981 non-null  int64
 7   address_state                  17981 non-null  object
 8   address_country                17981 non-null  object
 9   gender                         17981 non-null  object
 10  helix_community                16202 non-null  float64
 11  login_count_last_12m           17981 non-null  int64
 12  donation_page_visits_last_12m  17981 non-null  int64
 13  last_login_date                17981 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int64(5), object(5)
memory usage: 1.9+ MB

--- df_supporter head after cleaning ---

,supporter_id,registration_date,registration_channel,marketing_opt_in,preferred_channel,date_of_birth,address_postcode,address_state,address_country,gender,helix_community,login_count_last_12m,donation_page_visits_last_12m,last_login_date
0,100000,2022-04-30,Website,1,email,1981-01-10,7395,TAS,Australia,Female,100.0,33,13,2025-09-22
1,100001,2021-07-26,Event,1,email,1968-03-03,7363,TAS,Australia,Female,300.0,4,2,2025-05-17
2,100002,2021-05-17,Website,1,sms,1954-10-11,6282,WA,Australia,Female,600.0,1,0,2025-04-16
3,100003,2022-05-17,Social Media,0,email,1952-01-11,5641,SA,Australia,Female,200.0,27,11,2025-12-29
4,100004,2019-05-29,Website,1,whatsapp,NaT,851,NT,Australia,Female,200.0,6,1,2025-09-06

### 5. Handle Remaining Missing Values in `df_supporter` - `date_of_birth` and `helix_community`

We observed that `date_of_birth` and `helix_community` still contain missing values. We will handle these by:
- Filling `date_of_birth` `NaT` values with a placeholder date, such as '1900-01-01', to allow for age calculation and consistent data type.
- Filling `helix_community` `NaN` values with the median of the column to maintain distribution and provide a reasonable estimate.

In [28]:
# Fill NaT values in 'date_of_birth' with a placeholder date
df_supporter['date_of_birth'] = df_supporter['date_of_birth'].fillna(pd.to_datetime('1900-01-01'))

# Fill NaN values in 'helix_community' with the median
median_helix_community = df_supporter['helix_community'].median()
df_supporter['helix_community'] = df_supporter['helix_community'].fillna(median_helix_community)

print("--- df_supporter info after handling remaining missing values ---")
df_supporter.info()
print("\n--- df_supporter head after handling remaining missing values ---")
display(df_supporter.head())

--- df_supporter info after handling remaining missing values ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   supporter_id                   17981 non-null  int64
 1   registration_date              17981 non-null  datetime64[ns]
 2   registration_channel           17981 non-null  object
 3   marketing_opt_in               17981 non-null  int64
 4   preferred_channel              17981 non-null  object
 5   date_of_birth                  17981 non-null  datetime64[ns]
 6   address_postcode               17981 non-null  int64
 7   address_state                  17981 non-null  object
 8   address_country                17981 non-null  object
 9   gender                         17981 non-null  object
 10  helix_community                17981 non-null  float64
 11  login_count_last_12m           17981 non-null  int64
 12  donation_page_visits_last_12m  17981 non-null  int64
 13  last_login_date                17981 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int64(5), object(5)
memory usage: 1.9+ MB

--- df_supporter head after handling remaining missing values ---

,supporter_id,registration_date,registration_channel,marketing_opt_in,preferred_channel,date_of_birth,address_postcode,address_state,address_country,gender,helix_community,login_count_last_12m,donation_page_visits_last_12m,last_login_date
0,100000,2022-04-30,Website,1,email,1981-01-10,7395,TAS,Australia,Female,100.0,33,13,2025-09-22
1,100001,2021-07-26,Event,1,email,1968-03-03,7363,TAS,Australia,Female,300.0,4,2,2025-05-17
2,100002,2021-05-17,Website,1,sms,1954-10-11,6282,WA,Australia,Female,600.0,1,0,2025-04-16
3,100003,2022-05-17,Social Media,0,email,1952-01-11,5641,SA,Australia,Female,200.0,27,11,2025-12-29
4,100004,2019-05-29,Website,1,whatsapp,1900-01-01,851,NT,Australia,Female,200.0,6,1,2025-09-06

### 6. Final Verification of All Datasets After Cleaning

To ensure all cleaning and preprocessing steps were successful, let's re-check the information and null values for all four DataFrames. This will confirm that data types are correct and no missing values remain where they were handled.

In [29]:
for name, df in datasets.items():
    print(f"\n--- Info for {name} after cleaning ---")
    df.info()
    print(f"\n--- Null values in {name} after cleaning ---")
    print(df.isnull().sum())
    print("\n" + "="*50 + "\n") # Separator for readability

--- Info for supporter after cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   supporter_id                   17981 non-null  int64
 1   registration_date              17981 non-null  datetime64[ns]
 2   registration_channel           17981 non-null  object
 3   marketing_opt_in               17981 non-null  int64
 4   preferred_channel              17981 non-null  object
 5   date_of_birth                  17981 non-null  datetime64[ns]
 6   address_postcode               17981 non-null  int64
 7   address_state                  17981 non-null  object
 8   address_country                17981 non-null  object
 9   gender                         17981 non-null  object
 10  helix_community                17981 non-null  float64
 11  login_count_last_12m           17981 non-null  int64
 12  donation_page_visits_last_12m  17981 non-null  int64
 13  last_login_date                17981 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int64(5), object(5)
memory usage: 1.9+ MB

--- Null values in supporter after cleaning ---
supporter_id                     0
registration_date                0
registration_channel             0
marketing_opt_in                 0
preferred_channel                0
date_of_birth                    0
address_postcode                 0
address_state                    0
address_country                  0
gender                           0
helix_community                  0
login_count_last_12m             0
donation_page_visits_last_12m    0
last_login_date                  0
dtype: int64

==================================================


--- Info for campaigns_events after cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   campaign_id     50 non-null     int64
 1   campaign_type   50 non-null     object
 2   campaign_theme  50 non-null     object
 3   start_date      50 non-null     datetime64[ns]
 4   end_date        14 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 2.1+ KB

--- Null values in campaigns_events after cleaning ---
campaign_id        0
campaign_type      0
campaign_theme     0
start_date         0
end_date          36
dtype: int64

==================================================


--- Info for communications after cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   contact_id       90000 non-null  float64
 1   supporter_id     90000 non-null  int64
 2   campaign_id      90000 non-null  int64
 3   contact_date     90000 non-null  datetime64[ns]
 4   contact_channel  90000 non-null  object
 5   message_type     90000 non-null  object
 6   delivered        90000 non-null  int64
 7   opened           90000 non-null  int64
 8   clicked          90000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(2)
memory usage: 6.2+ MB

--- Null values in communications after cleaning ---
contact_id         0
supporter_id       0
campaign_id        0
contact_date       0
contact_channel    0
message_type       0
delivered          0
opened             0
clicked            0
dtype: int64

==================================================


--- Info for donations after cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   donation_id      35000 non-null  int64
 1   supporter_id     35000 non-null  int64
 2   donation_date    35000 non-null  datetime64[ns]
 3   donation_amount  35000 non-null  int64
 4   payment_channel  35000 non-null  object
 5   campaign_id      35000 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 1.6+ MB

--- Null values in donations after cleaning ---
donation_id        0
supporter_id       0
donation_date      0
donation_amount    0
payment_channel    0
campaign_id        0
dtype: int64

==================================================

### 7. Save Cleaned Datasets

In [30]:
output_dir = './cleaned_data'
import os


os.makedirs(output_dir, exist_ok=True)

for name, df in datasets.items():
    filename = f"{name}_cleaned.csv"
    filepath = os.path.join(output_dir, filename)
    df.to_csv(filepath, index=False)
    print(f"Saved cleaned '{name}' dataset to '{filepath}'")

print("\nAll cleaned datasets saved successfully!")

Saved cleaned 'supporter' dataset to './cleaned_data/supporter_cleaned.csv'
Saved cleaned 'campaigns_events' dataset to './cleaned_data/campaigns_events_cleaned.csv'
Saved cleaned 'communications' dataset to './cleaned_data/communications_cleaned.csv'
Saved cleaned 'donations' dataset to './cleaned_data/donations_cleaned.csv'

All cleaned datasets saved successfully!